name: sim_flights_tracker
description: Sim Flights Tracker is an app that tracks aircraft that are live on the Vatsim network. With this app you can see flight information, number of flights on the Vatsim network, and a lot of other flight related data. There is also a custom map that shows exactly where the aircraft are at any given time in their flight. This app (Sim Flights Tracker) is not endorsed by Vatsim. It is a personal project of the developer (Node-Ninja) that is offered free of charge.

publish_to: 'none'
version: 4.8.0+160

environment:
  sdk: '>=3.7.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  line_icons: ^2.0.3
  intl: ^0.20.2
  shared_preferences: ^2.2.1
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.1
  go_router: ^14.8.1
  lottie: ^3.3.1
  toggle_switch: ^2.3.0
  google_maps_flutter: ^2.12.2
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  google_nav_bar: ^5.0.6
  double_back_to_close_app: ^2.1.0
  dio: ^5.8.0+1
  material_symbols_icons: ^4.2808.0
  flutter_native_splash: ^2.4.5
  collection: ^1.17.0
  path_provider: ^2.1.2
  flutter_timeline_calendar:
    version: ^1.1.12
    git:
      url: https://github.com/Node-Ninja/flutter_timeline_calendar/
      ref: 9fd884e
  label_marker: ^1.0.1
  flutter_localizations:
    sdk: flutter
  dio_cache_interceptor: ^4.0.3
  http_cache_hive_store: ^5.0.1
  permission_handler: ^11.3.1
  firebase_core: ^3.2.0
  firebase_remote_config: ^5.4.2
  firebase_app_check: ^0.3.2+7
  firebase_analytics: ^11.5.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0
  get_it: ^8.0.3
  google_mobile_ads: ^5.3.1
  package_info_plus: ^8.3.0
  skeletonizer: ^2.0.1
  flutter_riverpod: ^2.6.1
  webview_flutter: ^4.13.0
  flutter_dotenv: ^5.2.1
  animate_do: ^4.2.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  source_gen: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  test: ^1.25.15

flutter_launcher_icons:


flutter_native_splash:
  android: true
  ios: true
  color: "#242A3C"
  image: assets/launcher_icon.png
  android_12:
    color: "#242A3C"
    image: assets/launcher_icon.png
    branding: assets/sft_text.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/vatsim/
    - assets/images/airlines/
    - assets/images/markers/
    - assets/data/
    - assets/lottie/
    - assets/
    - .env